spring:

  application:
    name: payment-orchestration-layer

  datasource:
    url: jdbc:postgresql://localhost:5432/payment_db
    username: postgres
    password: postgres
    spring:
      security:
        user:
          name: admin
          password: admin123

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

  cache:
    type: redis

  kafka:
    bootstrap-servers: localhost:9092